# HouseHolder

---
### Imports

In [1]:
# imports
import numpy as np
from numpy import dot,diagonal,outer,identity,matmul,transpose,zeros_like
from math import sqrt

### Definição de funções

In [2]:
norma = lambda x : np.sqrt(np.sum(np.square(x)))

# converter array 1d para vetor de coluna
def conv_col(x):
    x.shape = (1, x.shape[0])
    return x

# matriz HH para vetor v
def HH(v):
    tam_de_v = v.shape[1]
    e1 = zeros_like(v)
    e1[0, 0] = 1
    vector = norma(v) * e1
    if v[0, 0] < 0:
        vector = - vector
    u = (v + vector).astype(np.float32)
    m_identid = identity(tam_de_v)
    H = m_identid - ((2 * (u.T.dot(u))) / (u.dot(u.T)))
    return H

def it_qr_hh(q, r, iter, n):
    v = conv_col(r[iter:, iter])
    Hb = HH(v)
    H = identity(n)
    H[iter:, iter:] = Hb
    r = matmul(H, r)
    q = matmul(q, H)
    return q, r

### Matriz A de entrada

In [3]:
# dimensao da matriz
l, c = (4,4)
np.random.seed(0)
A = np.random.permutation(l*c).reshape((l,c)) + 1

print('Matriz A:\n', A)

Matriz A:
 [[ 2  7  9 10]
 [14  5  3 15]
 [11  8 16 12]
 [ 4  1  6 13]]


### Encontrar Q e R

In [4]:
Q = identity(l)
R = A.astype(np.float32)
for i in range(min(l, c)):
    Q, R = it_qr_hh(Q, R, i, l)

print('Matriz Q:\n', Q)
print('Matriz R:\n', R)
print('Validação:\n', np.allclose(A, np.dot(Q, R)))
print('Matriz Q * R:\n', np.dot(Q, R))

Matriz Q:
 [[-0.1089468   0.86793046  0.28657305 -0.39077214]
 [-0.76262856 -0.33687984  0.53284997 -0.1448462 ]
 [-0.59920818  0.32866326 -0.50704754  0.52519778]
 [-0.21789388 -0.15870979 -0.61388066 -0.74194609]]
Matriz R:
 [[-1.83575588e+01 -9.58732967e+00 -1.41631010e+01 -2.25520149e+01]
 [-1.84260749e-07  6.86171030e+00  1.11070880e+01  5.50683885e+00]
 [ 8.02813133e-08  2.14348100e-07 -7.61833721e+00 -3.20653906e+00]
 [ 7.75254647e-08  1.35077785e-07  1.92093323e-08 -9.42334025e+00]]
Validação:
 True
Matriz Q * R:
 [[ 1.99999713  6.99999631  8.99999448  9.99999422]
 [13.99999868  4.9999996   3.00000047 14.99999838]
 [10.99999929  7.99999834 15.99999674 11.99999771]
 [ 3.99999971  0.99999968  5.99999937 12.99999965]]


### Usando função do numpy para comparação

In [5]:
q, r = np.linalg.qr(A)
np.allclose(A, np.dot(q, r))

True

In [6]:
print('Matriz q:\n', q)
print('Matriz r:\n', r)

Matriz q:
 [[-0.10894694  0.86793062  0.28657306  0.39077216]
 [-0.76262859 -0.3368799   0.53285001  0.14484621]
 [-0.59920818  0.32866331 -0.5070476  -0.52519778]
 [-0.21789388 -0.15870978 -0.61388067  0.74194608]]
Matriz r:
 [[-18.35755975  -9.58733091 -14.16310248 -22.55201702]
 [  0.           6.8617116   11.10709023   5.50684033]
 [  0.           0.          -7.61833806  -3.20653917]
 [  0.           0.           0.           9.4233404 ]]
