# Decomposição QR com HouseHolder

---
### Imports

In [1]:
# imports
import numpy as np
from numpy import dot,diagonal,outer,identity,matmul,transpose,zeros_like
from math import sqrt

### Definição de funções

In [2]:
norma = lambda x : np.sqrt(np.sum(np.square(x)))

# converter array 1d para vetor de coluna
def conv_col(x):
    x.shape = (1, x.shape[0])
    return x

# matriz HH para vetor v
def HH(v):
    tam_de_v = v.shape[1]
    e1 = zeros_like(v)
    e1[0, 0] = 1
    vet = norma(v) * e1
    # funcao sinal (sign)
    if v[0, 0] < 0:
        vet = - vet
    u = (v + vet).astype(np.float32)
    m_identid = identity(tam_de_v)
    H = m_identid - ((2 * (u.T.dot(u))) / (u.dot(u.T)))
    return H

def it_qr_hh(q, r, iter, n):
    v = conv_col(r[iter:, iter])
    Hb = HH(v)
    H = identity(n)
    H[iter:, iter:] = Hb
    r = matmul(H, r)
    q = matmul(q, H)
    return q, r

### Matriz A de entrada

In [3]:
# dimensao da matriz
l, c = (4,4)
np.random.seed(0)
A = np.random.permutation(l*c).reshape((l,c)) + 1

print('Matriz A:\n', A)

Matriz A:
 [[ 2  7  9 10]
 [14  5  3 15]
 [11  8 16 12]
 [ 4  1  6 13]]


### Encontrar Q e R

In [4]:
Q = identity(l)
R = A.astype(np.float32)
for i in range(min(l, c)):
    Q, R = it_qr_hh(Q, R, i, l)

np.set_printoptions(suppress=True)
print('Matriz Q:\n', Q)
print('Matriz R:\n', np.around(R, decimals=10))
print('Validação:\n', np.allclose(A, np.dot(Q, R)))
print('Matriz Q * R:\n', np.dot(Q, R))

Matriz Q:
 [[-0.10894692  0.86793078  0.28657299 -0.39077214]
 [-0.76262861 -0.33687984  0.53285001 -0.14484625]
 [-0.59920824  0.32866332 -0.50704754  0.52519778]
 [-0.2178939  -0.15870975 -0.61388066 -0.7419461 ]]
Matriz R:
 [[-18.35756063  -9.5873313  -14.16310328 -22.55201793]
 [  0.0000013    6.86171309  11.10709216   5.50684329]
 [  0.00000045  -0.00000006  -7.61833777  -3.20653915]
 [ -0.00000052  -0.00000004  -0.00000007  -9.42334096]]
Validação:
 True
Matriz Q * R:
 [[ 2.00000114  7.00000223  9.00000388 10.00000326]
 [14.00000091  5.00000033  3.00000105 15.00000085]
 [11.00000145  8.0000013  16.00000136 12.00000233]
 [ 4.00000036  1.00000027  6.00000024 13.00000081]]


### Usando função do numpy para comparação

In [5]:
q, r = np.linalg.qr(A)
np.allclose(A, np.dot(q, r))

True

In [6]:
print('Matriz q:\n', q)
print('Matriz r:\n', r)

Matriz q:
 [[-0.10894694  0.86793062  0.28657306  0.39077216]
 [-0.76262859 -0.3368799   0.53285001  0.14484621]
 [-0.59920818  0.32866331 -0.5070476  -0.52519778]
 [-0.21789388 -0.15870978 -0.61388067  0.74194608]]
Matriz r:
 [[-18.35755975  -9.58733091 -14.16310248 -22.55201702]
 [  0.           6.8617116   11.10709023   5.50684033]
 [  0.           0.          -7.61833806  -3.20653917]
 [  0.           0.           0.           9.4233404 ]]
