# HouseHolder

In [1]:
# imports
import numpy as np
from numpy import dot,diagonal,outer,identity,matmul,transpose,zeros_like
from math import sqrt

In [2]:
def norma(x):
    return np.sqrt(np.sum(np.square(x)))

# converter array 1d para vetor de coluna
def conv_col(x):
    x.shape = (1, x.shape[0])
    return x

# matriz HH para vetor v
def HH(v):
    tam_de_v = v.shape[1]
    e1 = zeros_like(v)
    e1[0, 0] = 1
    vector = norma(v) * e1
    if v[0, 0] < 0:
        vector = - vector
    u = (v + vector).astype(np.float32)
    H = identity(tam_de_v) - ((2 * matmul(np.transpose(u), u)) / matmul(u, transpose(u)))
    return H

def it_qr_hh(q, r, iter, n):
    v = conv_col(r[iter:, iter])
    Hbar = HH(v)
    H = identity(n)
    H[iter:, iter:] = Hbar
    r = matmul(H, r)
    q = matmul(q, H)
    return q, r

In [3]:
# gerar matrizes aleatoriamente
# fixar random seed
np.random.seed(0)
# gerar matriz a (5 x 5)
a = np.random.permutation(4).reshape((2,2)) + 1
print(a)

#d,c = householder(a)
#p = computeP(a)
#print(d,c)

col_0 = a[0:, 0]
col_1 = a[0:, 1]

print(conv_col(col_0))
print(col_1)

[[3 4]
 [2 1]]
[[3 2]]
[4 1]


In [4]:
# dimensao da matriz
n, m = (4,4)
np.random.seed(0)
A = np.random.permutation(n*m).reshape((n,m)) + 1

print('Matriz A:\n', A)
Q = identity(n)
R = A.astype(np.float32)
for i in range(min(n, m)):
    # para cada iteracao, matriz H pe calculada para linha (i+1)
    Q, R = it_qr_hh(Q, R, i, n)

min_dim = min(m, n)
R = np.around(R, decimals=10)
R = R[:min_dim, :min_dim]
Q = np.around(Q, decimals=6)
print('Matriz R:\n', R)
print('Matriz Q:\n', Q)

Matriz A:
 [[ 2  7  9 10]
 [14  5  3 15]
 [11  8 16 12]
 [ 4  1  6 13]]
Matriz R:
 [[-1.83575588e+01 -9.58732967e+00 -1.41631010e+01 -2.25520149e+01]
 [-1.84300000e-07  6.86171030e+00  1.11070880e+01  5.50683885e+00]
 [ 8.03000000e-08  2.14300000e-07 -7.61833721e+00 -3.20653906e+00]
 [ 7.75000000e-08  1.35100000e-07  1.92000000e-08 -9.42334025e+00]]
Matriz Q:
 [[-0.108947  0.86793   0.286573 -0.390772]
 [-0.762629 -0.33688   0.53285  -0.144846]
 [-0.599208  0.328663 -0.507048  0.525198]
 [-0.217894 -0.15871  -0.613881 -0.741946]]
