# Método da potência deslocada

In [23]:
# imports
import numpy as np
import math

In [24]:
class MetodoPotencia(object):
    def __init__(self, a, b, it, desloc):
        self.a = a
        self.x = x
        self.it = it
        self.desloc = desloc
            
    def imprimeMatriz(self, msg, a, is_2d=False):
      print(msg)
      for l in range(0, len(a)):
          print('[', end='')
          if is_2d:
              for c in range(0, len(a[0])):
                  print(a[l][c], end=' ')
          else:
            print(a[l][0], end=' ')
          print(']')
            
      print("*"*49, '\n')
    
    
    def executaMP(self):
        maiorValor = None
        
        matrizIdent = np.identity(len(self.a))

        self.a = np.subtract(self.a, np.dot(self.desloc, matrizIdent))
        print("Matriz deslocada")
        print(self.a)
        for i in range(self.it):
            print("*"*49, '\n')
            print("Iteração número {}".format(i))
        
            produtoAX = np.dot(self.a, self.x)
            self.imprimeMatriz("Produto A x", produtoAX)
            maiorValor = max(produtoAX.min(), produtoAX.max(), key=abs)
            self.x = 1.0 / maiorValor * produtoAX
            self.imprimeMatriz("Resultado de x", self.x)
    
    def calculaAutovalor(self):
        produto = np.dot(self.a, self.x)
        print(produto)
        autovalor = produto[0]/self.x[0]
        print("Autovalor encontrado = {}".format(autovalor))
    
     
    def iniciaMP(self):
        self.executaMP()
        self.calculaAutovalor()

In [25]:
print("*"*15, "Método da Potência Deslocada", "*"*15)

a = np.array([[3.0, 0.0, 1.0], [2.0, 2.0, 2.0], [4.0, 2.0, 5.0]])
x = np.array([[1.0], [1.0], [1.0]])
    
mp = MetodoPotencia(a, x, 20, 7)
mp.imprimeMatriz("Matriz Original", mp.a, True)

*************** Método da Potência Deslocada ***************
Matriz Original
[3.0 0.0 1.0 ]
[2.0 2.0 2.0 ]
[4.0 2.0 5.0 ]
************************************************* 



In [26]:
mp.iniciaMP()

Matriz deslocada
[[-4.  0.  1.]
 [ 2. -5.  2.]
 [ 4.  2. -2.]]
************************************************* 

Iteração número 0
Produto A x
[-3.0 ]
[-1.0 ]
[4.0 ]
************************************************* 

Resultado de x
[-0.75 ]
[-0.25 ]
[1.0 ]
************************************************* 

************************************************* 

Iteração número 1
Produto A x
[4.0 ]
[1.75 ]
[-5.5 ]
************************************************* 

Resultado de x
[-0.7272727272727273 ]
[-0.3181818181818182 ]
[1.0 ]
************************************************* 

************************************************* 

Iteração número 2
Produto A x
[3.909090909090909 ]
[2.1363636363636362 ]
[-5.545454545454545 ]
************************************************* 

Resultado de x
[-0.7049180327868853 ]
[-0.38524590163934425 ]
[1.0 ]
************************************************* 

************************************************* 

Iteração número 3
Produto A x
[3.819672