# Mínimos Quadrados

---
### Imports

In [1]:
import numpy as np
from numpy import dot,diagonal,outer,identity,matmul,transpose,zeros_like
from math import sqrt
from numpy.linalg import inv as inversa

### Matrizes de entrada: A e b

In [2]:
#np.random.seed(31)
#A = (np.random.rand(6,4) * 20).round()
#print(A)

A = np.matrix('1 -1; 3 2; -2 4')
b = np.matrix('4; 1; 3')
print('A:\n', A, '\n')
print('b:\n', b, '\n')

A:
 [[ 1 -1]
 [ 3  2]
 [-2  4]] 

b:
 [[4]
 [1]
 [3]] 



### Solução de mínimos quadrados

In [3]:
def set_numpy_decimal_places(places, width=0):
    set_np = '{0:' + str(width) + '.' + str(places) + 'f}'
    np.set_printoptions(formatter={'float': lambda x: set_np.format(x)})

set_numpy_decimal_places(20)
AtA = (A.T * A)
AtB = (A.T * b)
invAtA = inversa(AtA)
x = invAtA * AtB

print('A.T * A:\n', AtA, '\n')
print('A.T * b:\n', AtB, '\n')

print('inv(AtA):\n', invAtA, '\n')
print('x = inv(AtA) * AtB (Vetor de solução):\n', x, '\n')

A.T * A:
 [[14 -3]
 [-3 21]] 

A.T * b:
 [[ 1]
 [10]] 

inv(AtA):
 [[0.07368421052631579649 0.01052631578947368397]
 [0.01052631578947368397 0.04912280701754385970]] 

x = inv(AtA) * AtB (Vetor de solução):
 [[0.17894736842105263275]
 [0.50175438596491228616]] 



### Vetor erro

In [4]:
vErr = (b - A * x)
print(vErr)

[[4.32280701754385976443]
 [-0.54035087719298235953]
 [1.35087719298245612087]]


### Erro

In [5]:
def norma(x):
    return np.sqrt(np.sum(np.square(x)))

print(norma(vErr))

4.561086358745012


### Bibliografia
Algebra Linear com Aplicações, página 366 seção 6.4