In [1]:
import numpy as np

In [2]:
np.random.seed(31)
A = (np.random.rand(6,4) * 20).round()
print(A)

[[ 6. 19. 15. 20.]
 [ 4.  3. 18.  1.]
 [ 2. 11.  2.  8.]
 [13.  9.  1.  4.]
 [ 9.  1.  6. 19.]
 [ 6.  5.  8. 17.]]


In [3]:
V = (np.random.rand(4,1) * 20).round()
print(V)

[[10.]
 [ 5.]
 [ 7.]
 [19.]]


# Resultado via Numpy (para comparação)

In [4]:
print(A.dot(V))

[[640.]
 [200.]
 [241.]
 [258.]
 [498.]
 [464.]]


# Exemplo calculando em blocos de 2x2

In [5]:
tam_blocos = 2
res = np.zeros((np.shape(A)[0],1))
print('Inicial:\n', res.T, '\n==============\n')
for l in range(0, np.shape(A)[0], tam_blocos):
    for c in range(0, np.shape(A)[1], tam_blocos):
        subm = A[l:l+tam_blocos,c:c+tam_blocos]
        subv = V[c:c+tam_blocos]
        print('Bloco A(', l, ',', c, ') a A(', l+tam_blocos, ',', c+tam_blocos,')\n', subm, ' * ', subv.T, '\nPreliminar:')
        print('Multiplicação do bloco: =>',subm.dot(subv).T)
        res[l:l+tam_blocos] += subm.dot(subv)
        print('Vetor atual => ', res.T, '\n------\n')

print('Final:\n', res)

Inicial:
 [[0. 0. 0. 0. 0. 0.]] 

Bloco A( 0 , 0 ) a A( 2 , 2 )
 [[ 6. 19.]
 [ 4.  3.]]  *  [[10.  5.]] 
Preliminar:
Multiplicação do bloco: => [[155.  55.]]
Vetor atual =>  [[155.  55.   0.   0.   0.   0.]] 
------

Bloco A( 0 , 2 ) a A( 2 , 4 )
 [[15. 20.]
 [18.  1.]]  *  [[ 7. 19.]] 
Preliminar:
Multiplicação do bloco: => [[485. 145.]]
Vetor atual =>  [[640. 200.   0.   0.   0.   0.]] 
------

Bloco A( 2 , 0 ) a A( 4 , 2 )
 [[ 2. 11.]
 [13.  9.]]  *  [[10.  5.]] 
Preliminar:
Multiplicação do bloco: => [[ 75. 175.]]
Vetor atual =>  [[640. 200.  75. 175.   0.   0.]] 
------

Bloco A( 2 , 2 ) a A( 4 , 4 )
 [[2. 8.]
 [1. 4.]]  *  [[ 7. 19.]] 
Preliminar:
Multiplicação do bloco: => [[166.  83.]]
Vetor atual =>  [[640. 200. 241. 258.   0.   0.]] 
------

Bloco A( 4 , 0 ) a A( 6 , 2 )
 [[9. 1.]
 [6. 5.]]  *  [[10.  5.]] 
Preliminar:
Multiplicação do bloco: => [[95. 85.]]
Vetor atual =>  [[640. 200. 241. 258.  95.  85.]] 
------

Bloco A( 4 , 2 ) a A( 6 , 4 )
 [[ 6. 19.]
 [ 8. 17.]]  *  [[ 