# produto vetorial de matrizes

In [1]:
# imports
import numpy as np

## Matriz A

In [2]:
# gerar matrizes aleatoriamente
# fixar random seed
np.random.seed(0)
# gerar matriz a (3 x 2)
a = np.random.permutation(6).reshape((3,2)) + 1
print(a)

[[6 3]
 [2 4]
 [1 5]]


## Vetor X

In [3]:
# outro seed e gerar com 2 elementos
np.random.seed(31)
#x = np.random.permutation(2).reshape((2,1)) + 1 * 3 / 5
x = np.random.permutation(2) + 1 * 3 / 5
x = np.ceil(x)
print(x)

[2. 1.]


## Matriz resultado

In [4]:
# matriz resultante
#nels = np.shape(a)[0] * np.shape(x)[1]
nels = np.shape(a)[0]
#res = np.zeros(nels).reshape((np.shape(a)[0],np.shape(x)[1]))
res = np.zeros(nels).reshape((np.shape(a)[0],1))
print(res)

[[0.]
 [0.]
 [0.]]


# Calcular com somatório

In [5]:
'''
# iteracao linhas m1
# calcula matriz x matrix
for l in range(0, np.shape(a)[0]):
    # iteracao colunas m2 (z)
    for z in range(0, np.shape(x)[1]):
        soma = 0
        for c in range(0, np.shape(a)[1]):
            soma = soma + (a[l, c] * x[c, z])
        res[l, z] = soma
print(res)
'''

# calcula matriz * vetor
for l in range(0, np.shape(a)[0]):
    # iteracao colunas m2 (z)
    soma = 0
    for c in range(0, np.shape(a)[1]):
        soma += (a[l, c] * x[c])
    res[l, 0] = soma
print(res)

[[15.]
 [ 8.]
 [ 7.]]


# Calcular direto na matriz resultante

In [6]:
# calcula matriz * vetor
iteracao = 0
res = np.zeros(np.shape(a)[0]) # limpar matriz resultado
for c in range(0, np.shape(a)[1]):
    for l in range(0, np.shape(a)[0]):
        res[l] += (a[l, c] * x[c])
        iteracao += 1
        # mostrar construção do resultado em cada iteração
        print('Iteracao', iteracao)
        print(res.reshape((np.shape(res)[0],1)))
        print('')

Iteracao 1
[[12.]
 [ 0.]
 [ 0.]]

Iteracao 2
[[12.]
 [ 4.]
 [ 0.]]

Iteracao 3
[[12.]
 [ 4.]
 [ 2.]]

Iteracao 4
[[15.]
 [ 4.]
 [ 2.]]

Iteracao 5
[[15.]
 [ 8.]
 [ 2.]]

Iteracao 6
[[15.]
 [ 8.]
 [ 7.]]

