In [1]:
# imports
import numpy as np
from numpy import dot,diagonal,outer,identity,matmul,transpose,zeros_like,sign
from math import sqrt
norma = lambda x : np.sqrt(np.sum(np.square(x)))

# converter array 1d para vetor de coluna
def conv_col(x):
    x.shape = (1, x.shape[0])
    return x

# dimensao da matriz
l, c = (4,4)
np.random.seed(0)
A = np.random.permutation(l*c).reshape((l,c)) + 1

print('Matriz A:\n', A, '\n')

a1 = conv_col(A[:,0]).T
n_a1 = norma(a1)
e1 = zeros_like(a1)
e1[0,0] = 1
sign_a11 = sign(a1[0])
v1 = a1 - (sign_a11 * n_a1 * e1)

print('a1:\n', a1, '\n')
print('norma(a1):\n', n_a1, '\n')
print('', v1, '\n')

i1 = identity(A.shape[1])

print('identidade:\n', i1, '\n')

H1 = i1 - 2 * (v1.dot(v1.T)) / (v1.T.dot(v1))
print('H1:\n', H1, '\n')

A2 = H1.dot(A)
print('A2:\n', np.around(A2, decimals=10), '\n')

Matriz A:
 [[ 2  7  9 10]
 [14  5  3 15]
 [11  8 16 12]
 [ 4  1  6 13]] 

a1:
 [[ 2]
 [14]
 [11]
 [ 4]] 

norma(a1):
 18.35755975068582 

 [[-16.35755975]
 [ 14.        ]
 [ 11.        ]
 [  4.        ]] 

identidade:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

H1:
 [[ 0.10894694  0.76262859  0.59920818  0.21789388]
 [ 0.76262859  0.34728648 -0.51284633 -0.18648958]
 [ 0.59920818 -0.51284633  0.59704931 -0.14652752]
 [ 0.21789388 -0.18648958 -0.14652752  0.94671726]] 

A2:
 [[18.35755975  9.58733091 14.16310248 22.55201702]
 [-0.          2.78557234 -1.41896198  4.25706273]
 [-0.          6.26009255 12.52795844  3.55912071]
 [ 0.          0.36730638  4.73743943  9.93058935]] 



Segue proxima iteracao onde era A1 agora é A2, até o a terceira iteracao, quando tiver H1 + H2 + H3

R = H3 * H2 * H1 * A

Q = H1 * H2 * H3

Referencias: https://atozmath.com/MatrixEv.aspx?q=qrdecomphh&q1=2%2c7%2c9%2c10%3b14%2c5%2c3%2c15%3b11%2c8%2c16%2c12%3b4%2c1%2c6%2c13%60qrdecomphh&dm=F&dp=8&do=1#PrevPart