# multiplicação de matrizes

In [1]:
# imports
import numpy as np

## Matriz 1 (m1)

In [2]:
# gerar matrizes aleatoriamente
# fixar random seed
np.random.seed(0)
# gerar matriz 1 (4 x 3)
m1 = np.random.permutation(12).reshape((4,3)) + 1
print(m1)

[[ 7 12  5]
 [11  3  9]
 [ 2  8 10]
 [ 4  1  6]]


## Matriz 2 (m2)

In [3]:
# outro seed e gerar matriz 2 (3 x 3)
np.random.seed(10)
m2 = np.random.permutation(9).reshape((3,3)) + 1 * 3 / 5
m2 = np.ceil(m2)
print(m2)

[[9. 3. 6.]
 [7. 4. 2.]
 [1. 8. 5.]]


## Matriz resultado

In [4]:
# matriz resultante
nels = np.shape(m1)[0] * np.shape(m2)[1]
res = np.zeros(nels).reshape((np.shape(m1)[0],np.shape(m2)[1]))
print(res)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Calcular

In [5]:
print('C','L')
# iteracao linhas m1
for y in range(0, np.shape(m1)[0]):
    # iteracao colunas m1
    for x in range(0, np.shape(m1)[1]):
        print(m1[x,y])
        print(m2[y,x])
        print('')

C L
7
9.0

11
3.0

2
6.0

12
7.0

3
4.0

8
2.0

5
1.0

9
8.0

10
5.0



IndexError: index 3 is out of bounds for axis 1 with size 3