# multiplicação de matrizes

In [11]:
# imports
import numpy as np

## Matriz 1 (m1)

In [12]:
# gerar matrizes aleatoriamente
# fixar random seed
np.random.seed(0)
# gerar matriz 1 (3 x 2)
m1 = np.random.permutation(6).reshape((3,2)) + 1
print(m1)

[[6 3]
 [2 4]
 [1 5]]


## Matriz 2 (m2)

In [13]:
# outro seed e gerar matriz 2 (2 x 2)
np.random.seed(10)
m2 = np.random.permutation(4).reshape((2,2)) + 1 * 3 / 5
m2 = np.ceil(m2)
print(m2)

[[3. 1.]
 [4. 2.]]


## Matriz resultado

In [14]:
# matriz resultante
nels = np.shape(m1)[0] * np.shape(m2)[1]
res = np.zeros(nels).reshape((np.shape(m1)[0],np.shape(m2)[1]))
print(res)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


# Calcular com somatório

In [15]:
# iteracao linhas m1
for l in range(0, np.shape(m1)[0]):
    # iteracao colunas m2 (z)
    for z in range(0, np.shape(m2)[1]):
        soma = 0
        for c in range(0, np.shape(m1)[1]):
            soma = soma + (m1[l, c] * m2[c, z])
        res[l, z] = soma
print(res)

[[30. 12.]
 [22. 10.]
 [23. 11.]]


# Calcular direto na matriz resultante

In [17]:
# zerar
res = np.zeros(nels).reshape((np.shape(m1)[0],np.shape(m2)[1]))
# iteracao colunas m1
for c in range(0, np.shape(m1)[1]):
    for l in range(0, np.shape(m1)[0]):
        print(l, c)
print(res)

0 0
1 0
2 0
0 1
1 1
2 1
[[0. 0.]
 [0. 0.]
 [0. 0.]]
